job_1: {F: '006', init_date: '20250808'}
job_10: {F: '060', init_date: '20250808'}
job_11: {F: '066', init_date: '20250808'}
job_12: {F: '072', init_date: '20250808'}
job_13: {F: 078, init_date: '20250808'}
job_14: {F: 084, init_date: '20250808'}
job_15: {F: 090, init_date: '20250808'}
job_16: {F: 096, init_date: '20250808'}
job_17: {F: '102', init_date: '20250808'}
job_18: {F: '108', init_date: '20250808'}
job_19: {F: '114', init_date: '20250808'}
job_2: {F: '012', init_date: '20250808'}
job_20: {F: '120', init_date: '20250808'}
job_21: {F: '126', init_date: '20250808'}
job_22: {F: '132', init_date: '20250808'}
job_23: {F: '138', init_date: '20250808'}
job_24: {F: '144', init_date: '20250808'}
job_25: {F: '150', init_date: '20250808'}
job_26: {F: '156', init_date: '20250808'}
job_27: {F: '162', init_date: '20250808'}
job_28: {F: '168', init_date: '20250808'}
job_3: {F: 018, init_date: '20250808'}
job_4: {F: '024', init_date: '20250808'}
job_5: {F: '030', init_date: '20250808'}
job_6: {F: '036', init_date: '20250808'}
job_7: {F: '042', init_date: '20250808'}
job_8: {F: 048, init_date: '20250808'}
job_9: {F: '054', init_date: '20250808'}
