job_1: {F: '006', init_date: '20250915'}
job_10: {F: '060', init_date: '20250915'}
job_11: {F: '066', init_date: '20250915'}
job_12: {F: '072', init_date: '20250915'}
job_13: {F: 078, init_date: '20250915'}
job_14: {F: 084, init_date: '20250915'}
job_15: {F: 090, init_date: '20250915'}
job_16: {F: 096, init_date: '20250915'}
job_17: {F: '102', init_date: '20250915'}
job_18: {F: '108', init_date: '20250915'}
job_19: {F: '114', init_date: '20250915'}
job_2: {F: '012', init_date: '20250915'}
job_20: {F: '120', init_date: '20250915'}
job_21: {F: '126', init_date: '20250915'}
job_22: {F: '132', init_date: '20250915'}
job_23: {F: '138', init_date: '20250915'}
job_24: {F: '144', init_date: '20250915'}
job_25: {F: '150', init_date: '20250915'}
job_26: {F: '156', init_date: '20250915'}
job_27: {F: '162', init_date: '20250915'}
job_28: {F: '168', init_date: '20250915'}
job_29: {F: '006', init_date: '20250919'}
job_3: {F: 018, init_date: '20250915'}
job_30: {F: '012', init_date: '20250919'}
job_31: {F: 018, init_date: '20250919'}
job_32: {F: '024', init_date: '20250919'}
job_33: {F: '030', init_date: '20250919'}
job_34: {F: '036', init_date: '20250919'}
job_35: {F: '042', init_date: '20250919'}
job_36: {F: 048, init_date: '20250919'}
job_37: {F: '054', init_date: '20250919'}
job_38: {F: '060', init_date: '20250919'}
job_39: {F: '066', init_date: '20250919'}
job_4: {F: '024', init_date: '20250915'}
job_40: {F: '072', init_date: '20250919'}
job_41: {F: 078, init_date: '20250919'}
job_42: {F: 084, init_date: '20250919'}
job_43: {F: 090, init_date: '20250919'}
job_44: {F: 096, init_date: '20250919'}
job_45: {F: '102', init_date: '20250919'}
job_46: {F: '108', init_date: '20250919'}
job_47: {F: '114', init_date: '20250919'}
job_48: {F: '120', init_date: '20250919'}
job_49: {F: '126', init_date: '20250919'}
job_5: {F: '030', init_date: '20250915'}
job_50: {F: '132', init_date: '20250919'}
job_51: {F: '138', init_date: '20250919'}
job_52: {F: '144', init_date: '20250919'}
job_53: {F: '150', init_date: '20250919'}
job_54: {F: '156', init_date: '20250919'}
job_55: {F: '162', init_date: '20250919'}
job_56: {F: '168', init_date: '20250919'}
job_57: {F: '006', init_date: '20251008'}
job_58: {F: '012', init_date: '20251008'}
job_59: {F: 018, init_date: '20251008'}
job_6: {F: '036', init_date: '20250915'}
job_60: {F: '024', init_date: '20251008'}
job_61: {F: '030', init_date: '20251008'}
job_62: {F: '036', init_date: '20251008'}
job_63: {F: '042', init_date: '20251008'}
job_64: {F: 048, init_date: '20251008'}
job_65: {F: '054', init_date: '20251008'}
job_66: {F: '060', init_date: '20251008'}
job_67: {F: '066', init_date: '20251008'}
job_68: {F: '072', init_date: '20251008'}
job_69: {F: 078, init_date: '20251008'}
job_7: {F: '042', init_date: '20250915'}
job_70: {F: 084, init_date: '20251008'}
job_71: {F: 090, init_date: '20251008'}
job_72: {F: 096, init_date: '20251008'}
job_73: {F: '102', init_date: '20251008'}
job_74: {F: '108', init_date: '20251008'}
job_75: {F: '114', init_date: '20251008'}
job_76: {F: '120', init_date: '20251008'}
job_77: {F: '126', init_date: '20251008'}
job_78: {F: '132', init_date: '20251008'}
job_79: {F: '138', init_date: '20251008'}
job_8: {F: 048, init_date: '20250915'}
job_80: {F: '144', init_date: '20251008'}
job_81: {F: '150', init_date: '20251008'}
job_82: {F: '156', init_date: '20251008'}
job_83: {F: '162', init_date: '20251008'}
job_84: {F: '168', init_date: '20251008'}
job_9: {F: '054', init_date: '20250915'}
