# Filename:    ERA5_config.yml
# Author:      Deanna Nash, dlnash@ucsb.edu
# Description: Dictionary of different download variables/options for ERA5
# for use in conjunction with getERA5_batch.py and download_ERA5.sh

--- 
ivt:
    data_type: 'reanalysis-era5-single-levels'
    var_name: ['vertical_integral_of_northward_water_vapour_flux', 'vertical_integral_of_eastward_water_vapour_flux']
    start_yr: 2020
    end_yr: 2020
    month: ['01','02','03','04','05','06','07','08','09','10','11','12']
    day: ['01','02','03','04','05','06', '07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31']
    time: ['00:00', '06:00', '12:00', '18:00']
    area: [19, -180, 80, -110] # [N,W,S,E] Default: global
    grid: [0.25, 0.25]
    datadir: '/cw3e/mead/projects/cwp140/scratch/dnash/data/downloads/ERA5/ivt/6hr/'
    fprefix: "era5_ak_025dg_6hr_ivt"
...